"""db_creation6

Revision ID: 590c24b8b1aa
Revises: 
Create Date: 2023-09-20 23:10:25.230104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590c24b8b1aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
